name: sunapsis_conference18
description: App for sunapsis Conference 2018, made with Flutter. App provides schedule or the entire conference.

version: 1.0.3+4

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.0
  firebase_auth: ^0.5.20
  rxdart: ^0.18.1
  url_launcher: ^3.0.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^3.0.0
  flutter_launcher_icons: ^0.6.1


flutter:
  uses-material-design: true
  assets:
    - res/sunapsislogo.png
    - res/splashscreen.jpg
    - res/avatar_placeholder.png
    - res/sunapsis-conference-logo-01.png
    - res/twitter.png

flutter_icons:
  android: true
  ios: "app-icon"
  image_path: "res/conficon.png"
  adaptive_icon_background: "#FF44697D"
  adaptive_icon_foreground: "res/fedora.png"